# Generated by Django 5.2.7 on 2025-10-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom',
            name='Role',
            field=models.CharField(choices=[('Student', 'Student'), ('Faculty', 'Faculty'), ('Admin', 'Admin'), ('TransportMem', 'TransportMem')]),
        ),
        migrations.DeleteModel(
            name='student_basic_detail',
        ),
    ]
