# Generated by Django 5.2.7 on 2025-12-31 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddeRecordLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Books', models.CharField(max_length=12)),
                ('Total_Student', models.CharField(max_length=12)),
                ('Total_System', models.CharField(max_length=12)),
                ('Day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')])),
            ],
        ),
        migrations.CreateModel(
            name='LibrarianDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Librarian_Id', models.CharField(max_length=12)),
                ('Course', models.CharField(choices=[('Btech', 'Btech'), ('Management', 'Management'), ('Bsc Agricuture', 'Bsc Agriculture'), ('BSC Nursing', 'Bsc Nursing'), ('BCA', 'BCA'), ('LAW', 'LAW'), ('MCA', 'MCA'), ('Mtech', 'Mtech'), ('MBBS', 'MBBS'), ('Art Science', 'Art Science')])),
                ('Library_id', models.CharField(max_length=10)),
                ('No_of_department', models.CharField(max_length=12)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
