# Generated by Django 5.2.7 on 2025-10-24 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facultyman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_id', models.CharField(blank='True', max_length=12, null=True)),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=30)),
                ('profile_image', models.ImageField(upload_to='Facultymanage/faculty/')),
                ('Department', models.CharField(max_length=23)),
                ('positions', models.CharField(max_length=30)),
                ('experience', models.CharField(max_length=10)),
                ('Course', models.CharField(choices=[('Btech', 'Btech'), ('Management', 'Management'), ('Bsc Agricuture', 'Bsc Agriculture'), ('BSC Nursing', 'Bsc Nursing'), ('BCA', 'BCA'), ('LAW', 'LAW'), ('MCA', 'MCA'), ('Mtech', 'Mtech'), ('MBBS', 'MBBS'), ('Art Science', 'Art Science')], default='Select Corse', max_length=50)),
                ('Branch', models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('IT', 'Information Technology'), ('ECE', 'Electronics and Communication Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('AE', 'Automobile Engineering'), ('CHE', 'Chemical Engineering'), ('BT', 'Biotechnology'), ('AERO', 'Aerospace Engineering'), ('MIN', 'Mining Engineering'), ('MT', 'Metallurgical Engineering'), ('DS', 'Data Science'), ('AI', 'Artificial Intelligence & Machine Learning'), ('IOT', 'Internet of Things'), ('ROBO', 'Robotics and Automation'), ('ENV', 'Environmental Engineering'), ('MBBS', 'Bachelor of Medicine, Bachelor of Surgery'), ('BDS', 'Bachelor of Dental Surgery'), ('BPT', 'Bachelor of Physiotherapy'), ('BPHARM', 'Bachelor of Pharmacy'), ('NURS', 'Nursing'), ('BSC', 'Bachelor of Science'), ('MSC', 'Master of Science'), ('BSTAT', 'Bachelor of Statistics'), ('BCOM', 'Bachelor of Commerce'), ('MCOM', 'Master of Commerce'), ('BBA', 'Bachelor of Business Administration'), ('MBA', 'Master of Business Administration'), ('BBM', 'Bachelor of Business Management'), ('BSC_AGRI', 'B.Sc Agriculture'), ('BSC_HORT', 'B.Sc Horticulture'), ('BSC_FOREST', 'B.Sc Forestry')], default='Select Branch', max_length=80)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
