# Generated by Django 5.2.7 on 2025-10-26 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransportDomain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_passenger', models.PositiveIntegerField()),
                ('Total_student', models.PositiveIntegerField()),
                ('Total_faculty', models.PositiveIntegerField()),
                ('Day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')])),
                ('Bus_Plate_number', models.CharField(max_length=10)),
                ('date', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='TransportDomain.transport_mem')),
            ],
        ),
    ]
