# Generated by Django 5.2.7 on 2025-10-26 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransportDomain', '0002_dailydetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydetail',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='TransportDomain.transport_mem'),
        ),
    ]
