# Generated by Django 5.2.7 on 2025-10-26 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransportDomain', '0003_alter_dailydetail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydetail',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
