# Generated by Django 5.2.7 on 2025-10-24 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='student_basic_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank='', max_length=12, null=True)),
                ('first_name', models.CharField(blank='', max_length=50, null=True)),
                ('last_name', models.CharField(blank='', max_length=50, null=True)),
                ('mother_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('Permanent_address', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('AP', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BR', 'Bihar'), ('CT', 'Chhattisgarh'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('HR', 'Haryana'), ('HP', 'Himachal Pradesh'), ('JH', 'Jharkhand'), ('KA', 'Karnataka'), ('KL', 'Kerala'), ('MP', 'Madhya Pradesh'), ('MH', 'Maharashtra'), ('MN', 'Manipur'), ('ML', 'Meghalaya'), ('MZ', 'Mizoram'), ('NL', 'Nagaland'), ('OD', 'Odisha'), ('PB', 'Punjab'), ('RJ', 'Rajasthan'), ('SK', 'Sikkim'), ('TN', 'Tamil Nadu'), ('TG', 'Telangana'), ('TR', 'Tripura'), ('UP', 'Uttar Pradesh'), ('UK', 'Uttarakhand'), ('WB', 'West Bengal'), ('AN', 'Andaman and Nicobar Islands'), ('CH', 'Chandigarh'), ('DN', 'Dadra and Nagar Haveli and Daman and Diu'), ('DL', 'Delhi'), ('JK', 'Jammu and Kashmir'), ('LA', 'Ladakh'), ('LD', 'Lakshadweep'), ('PY', 'Puducherry')], default='Select State', max_length=50)),
                ('pin_code', models.IntegerField(blank=True, null=True)),
                ('local_address', models.CharField(max_length=80)),
                ('profile_image', models.ImageField(upload_to='student/images/')),
                ('signature', models.ImageField(upload_to='student/signature/')),
                ('mobile_number', models.CharField(max_length=12, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('blood_group', models.CharField(max_length=5)),
                ('pancard_number', models.CharField(max_length=12)),
                ('High_marksheet', models.FileField(upload_to='student/document/')),
                ('Inter_marksheet', models.FileField(upload_to='student/document/')),
                ('Migrations', models.FileField(upload_to='student/document/')),
                ('Character_cirtificate', models.FileField(upload_to='student/document/')),
                ('TC', models.FileField(upload_to='student/document/')),
                ('Aadhar', models.FileField(upload_to='student/document/')),
                ('high_passout', models.CharField(blank='2000', max_length=30, null=True)),
                ('inter_passout', models.CharField(blank='2000', max_length=30, null=True)),
                ('high_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('inter_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('Course', models.CharField(choices=[('Btech', 'Btech'), ('Management', 'Management'), ('Bsc Agricuture', 'Bsc Agriculture'), ('BSC Nursing', 'Bsc Nursing'), ('BCA', 'BCA'), ('LAW', 'LAW'), ('MCA', 'MCA'), ('Mtech', 'Mtech'), ('MBBS', 'MBBS'), ('Art Science', 'Art Science')], default='Select Course', max_length=50)),
                ('Branch', models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('IT', 'Information Technology'), ('ECE', 'Electronics and Communication Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('AE', 'Automobile Engineering'), ('CHE', 'Chemical Engineering'), ('BT', 'Biotechnology'), ('AERO', 'Aerospace Engineering'), ('MIN', 'Mining Engineering'), ('MT', 'Metallurgical Engineering'), ('DS', 'Data Science'), ('AI', 'Artificial Intelligence & Machine Learning'), ('IOT', 'Internet of Things'), ('ROBO', 'Robotics and Automation'), ('ENV', 'Environmental Engineering'), ('MBBS', 'Bachelor of Medicine, Bachelor of Surgery'), ('BDS', 'Bachelor of Dental Surgery'), ('BPT', 'Bachelor of Physiotherapy'), ('BPHARM', 'Bachelor of Pharmacy'), ('NURS', 'Nursing'), ('BSC', 'Bachelor of Science'), ('MSC', 'Master of Science'), ('BSTAT', 'Bachelor of Statistics'), ('BCOM', 'Bachelor of Commerce'), ('MCOM', 'Master of Commerce'), ('BBA', 'Bachelor of Business Administration'), ('MBA', 'Master of Business Administration'), ('BBM', 'Bachelor of Business Management'), ('BSC_AGRI', 'B.Sc Agriculture'), ('BSC_HORT', 'B.Sc Horticulture'), ('BSC_FOREST', 'B.Sc Forestry')], default='Select Branch', max_length=80)),
                ('Dob', models.DateField()),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
